---
- name: Restart flask-app
  systemd:
    name: flask-app
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes

- name: Enable docker compose service
  systemd:
    name: flask-app-docker
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes