---
- name: Restart flask-app
  systemd:
    name: flask-app
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes